### PR TITLE
Added the selection sort algorithm in sort visualizer

### PR DESCRIPTION
**Pull request by vandana1499**
#6 
It is working fine.I guess there is an issue with UI. It's visible on the mobile device.

### CODE REVIEW

**Comment by anubhavitis** [comment]
> #6
> It is working fine.I guess there is an issue with UI. It's visible on the mobile device.

There are no UI issues, You have to write a selection sort algorithm, cause function is incomplete.
Read issue description for more information.

**Comment by vandana1499** [comment]
Yes, I have completed the function . I have written the selection sort algorithm.

**Comment by ayush-tiwari57** [comment]
hey @vandana1499 thanx for contributing. We will review your code and get back to you in a while

**Comment by anubhavitis** [comment]
Hello,
we have made some changes to our hosted server, which is creating conflicts with your current PR. So I request you to close this pull request and add it again so that we can preview it and proceed further towards verification/merge.

Sorry for the inconvenience.
You can also join our slack channel for updates/ discussion.

**Pull request closed without merging**
