### PR TITLE
Update css and html on the main page

### PR DESCRIPTION
**Pull request by STM3900**
I hope you'll like it!

### CODE REVIEW

**Comment by anubhavitis** [comment]
Hey, I like what you did with a navbar, it's great.

But for the rest of the page, we can't go with those colored cards and white background (As it doesn't match with the rest of the pages), we would rather like to keep it the old way, so unless you can give us a better UI for the homepage, remove all the changes (except for the navbar), and we are good to go.  

Also, you can add our logo before the 'Algorithm Visualizer' link in Navbar (png is available)

**Comment by STM3900** [comment]
Okay I will make an another version later this day ! (It's okay if i just put the previous background color and change the color of the cards ?)

**Comment by anubhavitis** [comment]
Yeah, restore the previous background color, and put logo1.png in the navbar in home link.

**Comment by STM3900** [comment]
I made a new PR with the changes here #18 !

**Pull request closed without merging**
