### PR TITLE
Added the insertion and selection algorithm

### PR DESCRIPTION
**Pull request by vandana1499**
#6 
#7 
Added the insertion and selection algorithm.

### CODE REVIEW

**Comment by anubhavitis** [comment]
Both insertion and selection sort algorithms are not working in the visualizer.

**Comment by vandana1499** [comment]
> Both insertion and selection sort algorithms are not working in the visualizer.

I will attach image of working algorithm . I was mentioning the same thing before.  The bubble sort algorithm is also not working . All these algorithm including bubble sort algorithm is working in smaller device size ...

**Comment by vandana1499** [comment]
Screenshot (93)
Screenshot (94)
Screenshot (95)

**Comment by vandana1499** [comment]
@servermonk Will u please let me know the problem with code?

**Pull request closed without merging**
