### PR TITLE
Fix logo path

### PR DESCRIPTION
**Pull request by KonradLinkowski**
I changed the path because the server couldn't resolve the logo path in the main page

### CODE REVIEW

**Comment by anubhavitis** [comment]
Hello,
we have made some changes to our hosted server, which is creating conflicts with your current PR. So I request you to close this pull request and add it again so that we can preview it and proceed further towards verification/merge.

Sorry for the inconvenience.
You can also join our slack channel for updates/ discussion.

**Comment by KonradLinkowski** [comment]
@anubhavitis  Hmm it says that there are no conflicts, so recreating PR would probably change nothing. Should I change the target branch?

**Comment by ayush-tiwari57** [comment]
hii @KonradLinkowski actually to have to make pr to the beta branch and not the master branch so you have to change the target branch

**Comment by KonradLinkowski** [comment]
@servermonk done ✔️

**Comment by anubhavitis** [comment]
@KonradLinkowski, Logo path wasn't showing any error.

**Pull request closed without merging**
